# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 1.0.1
# test_defaults:
#   before_plan:
#     - cp -a /mnt/workspace/source/examples/test_infrastructure/additional_outputs/. ../../  
  # after_apply:
  #   - >
  #     exit_code=0;
  #     for file in $(ls -1 expected/); do
  #       cat expected/$file | jq --sort-keys > jq_expected_$file;
  #       cat produced_$file | jq --sort-keys > jq_produced_$file;
  #       if ! diff <(sed '/"myPath": /,/uri/d' jq_expected_$file) <(sed '/"myPath": /,/uri/d' jq_produced_$file); then
  #         exit_code=1;
  #       fi;
  #     done;
  #     exit $exit_code;
#   environment:
#     AWS_REGION: us-east-2
# tests:
#   - name: Simple API GatewayV1 Test
#     project_root: examples/simple